locates {
    windows-esp {
        by_file = "/EFI/Microsoft/Boot/bootmgfw.efi"
    }
    twrp-image {
        by_file = "/twrp-munch.img"
    }
}

boot {
    title = "Redmi K40S Boot Menu"
    default = "windows"
    timeout = 3
    timeout_text = "Starting Windows in %d seconds"
    console_log = false
    uefi_probe = false
    uefi_bootmenu = true

    configs {
        windows {
            mode = "efi"
            desc = "Windows 11 ARM"
            show = true
            enabled = true
            icon = "uefi.svg"
            extra {
                efi_file = "@windows-esp:/EFI/Microsoft/Boot/bootmgfw.efi"
            }
        }

        twrp {
            mode = "linux"
            desc = "TWRP Recovery"
            show = true
            enabled = true
            icon = "abootimg.svg"
            extra {
                abootimg = "@twrp-image:/twrp-munch.img"
                use_efi = false
            }
        }

        android {
            mode = "efi"
            desc = "Reboot to Android"
            show = true
            enabled = true
            icon = "abootimg.svg"
            extra {
                efi_fv_guid = "801a189c-e4a4-4195-85c2-64c5450a15ee"
            }
        }

        fastboot {
            mode = "reboot"
            desc = "Reboot to Fastboot"
            show = true
            enabled = true
            icon = "reboot.svg"
            extra {
                arg = "bootloader"
            }
        }

        recovery {
            mode = "reboot"
            desc = "Reboot to Stock Recovery"
            show = true
            enabled = true
            icon = "reboot.svg"
            extra {
                arg = "recovery"
            }
        }

        continue {
            mode = "exit"
            desc = "Continue UEFI Boot"
            show = true
            enabled = true
            icon = "uefi.svg"
        }
    }
}
